CREATE TABLE dokter (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_dokter VARCHAR(100) NOT NULL,
    spesialis VARCHAR(50) NOT NULL,
    tarif_jasa DECIMAL(12, 2) NOT NULL CHECK (tarif_jasa >= 0),
    kuota_harian INT NOT NULL DEFAULT 30 CHECK (kuota_harian > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'pendaftaran' CHECK (role IN ('pendaftaran', 'dokter', 'kasir', 'admin')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pasien (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik VARCHAR(16) NOT NULL UNIQUE,
    nama_lengkap VARCHAR(100) NOT NULL,
    jenis_kelamin VARCHAR(10) CHECK (jenis_kelamin IN ('Laki-laki', 'Perempuan')),
    tanggal_lahir DATE NOT NULL,
    telepon VARCHAR(15),
    alamat TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE obat (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_obat VARCHAR(100) NOT NULL,
    harga_satuan DECIMAL(12, 2) NOT NULL CHECK (harga_satuan >= 0),
    stok INT NOT NULL DEFAULT 0 CHECK (stok >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE antrean (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pasien_id INT NOT NULL REFERENCES pasien(id),
    dokter_id INT NOT NULL REFERENCES dokter(id),
    tanggal_berobat DATE NOT NULL DEFAULT CURRENT_DATE,
    nomor_antrean INT NOT NULL CHECK (nomor_antrean > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'Menunggu' CHECK (status IN ('Menunggu', 'Periksa', 'Selesai', 'Batal')),
    alasan_batal TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rekam_medis (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pasien_id INT NOT NULL REFERENCES pasien(id),
    antrean_id INT NOT NULL UNIQUE REFERENCES antrean(id),
    diagnosa TEXT NOT NULL,
    catatan_dokter TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE resep_detail (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rekam_medis_id INT NOT NULL REFERENCES rekam_medis(id) ON DELETE CASCADE,
    obat_id INT NOT NULL REFERENCES obat(id),
    jumlah INT NOT NULL CHECK (jumlah > 0),
    subtotal DECIMAL(12, 2) NOT NULL CHECK (subtotal >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pembayaran (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    antrean_id INT NOT NULL UNIQUE REFERENCES antrean(id),
    total_bruto DECIMAL(12, 2) NOT NULL CHECK (total_bruto >= 0),
    diskon_persen DECIMAL(5, 2) NOT NULL DEFAULT 0 CHECK (diskon_persen BETWEEN 0 AND 100),
    total_netto DECIMAL(12, 2) NOT NULL CHECK (total_netto >= 0),
    metode_pembayaran VARCHAR(20) NOT NULL DEFAULT 'Cash' CHECK (metode_pembayaran IN ('Cash', 'QRIS', 'Transfer', 'Debit')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE log_aktivitas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pengguna VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    aksi VARCHAR(50) NOT NULL,
    id_referensi INT NULL,
    keterangan TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pasien_nik ON pasien USING btree (nik);
CREATE INDEX idx_antrean_tgl_dokter ON antrean USING btree (tanggal_berobat, dokter_id);
CREATE INDEX idx_antrean_tgl_status ON antrean USING btree (tanggal_berobat, status);
CREATE INDEX idx_rekam_medis_pasien ON rekam_medis USING btree (pasien_id);
CREATE INDEX idx_obat_nama ON obat USING btree (nama_obat);
CREATE INDEX idx_pembayaran_antrean ON pembayaran USING btree (antrean_id);