CREATE TABLE dokter (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_dokter VARCHAR(100) NOT NULL,
    spesialis VARCHAR(50) NOT NULL,
    tarif_jasa DECIMAL(12, 2) NOT NULL CHECK (tarif_jasa >= 0),
    kuota_harian INT NOT NULL DEFAULT 30,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'pendaftaran',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE obat (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_obat VARCHAR(100) NOT NULL,
    harga_satuan DECIMAL(12, 2) NOT NULL CHECK (harga_satuan >= 0),
    stok INT NOT NULL DEFAULT 0 CHECK (stok >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pasien (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik VARCHAR(16) NOT NULL UNIQUE,
    nama_lengkap VARCHAR(100) NOT NULL,
    tanggal_lahir DATE NOT NULL,
    telepon VARCHAR(15),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE antrean (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pasien_id INT NOT NULL REFERENCES pasien(id),
    dokter_id INT NOT NULL REFERENCES dokter(id),
    tanggal_berobat DATE NOT NULL DEFAULT CURRENT_DATE,
    nomor_antrean INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Menunggu',
    metadata_json JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rekam_medis (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    antrean_id INT NOT NULL UNIQUE REFERENCES antrean(id),
    diagnosa TEXT NOT NULL,
    catatan_json JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE resep_detail (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rekam_medis_id INT NOT NULL REFERENCES rekam_medis(id) ON DELETE CASCADE,
    obat_id INT NOT NULL REFERENCES obat(id),
    jumlah INT NOT NULL CHECK (jumlah > 0),
    subtotal DECIMAL(12, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pembayaran (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    antrean_id INT NOT NULL UNIQUE REFERENCES antrean(id),
    total_bruto DECIMAL(12, 2) NOT NULL,
    diskon_persen DECIMAL(5, 2) NOT NULL DEFAULT 0,
    total_netto DECIMAL(12, 2) NOT NULL,
    metode_json JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE log_aktivitas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sumber_event VARCHAR(50) NOT NULL,
    keterangan TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pasien_nik ON pasien USING btree (nik);
CREATE INDEX idx_antrean_tgl_dokter ON antrean USING btree (tanggal_berobat, dokter_id);
CREATE INDEX idx_obat_nama ON obat USING btree (nama_obat);
CREATE INDEX idx_pembayaran_antrean ON pembayaran USING btree (antrean_id);
CREATE INDEX idx_antrean_tgl_status ON antrean USING btree (tanggal_berobat, status);