services:
  postgres:
    image: postgres:16-alpine
    container_name: mbd_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_clinic_db
    ports:
      - "5432:5432" # Atau 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Web GUI Database (Adminer)
  adminer:
    image: adminer
    container_name: mbd_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: